### PR TITLE
Call the callback when `flush()` is complete in order to signal stream read end

### PR DESCRIPTION
**Pull request by gregjacobs**
Hey man, thanks for putting this plugin together.

Added a call to the through2 `flush()` callback in order to signal Gulp when the JSDuck task is complete. Needed to add this so that I could copy my example files in afterwards. (JSDuck clears the output directory when executed so if it's still executing when the example files are copied in, the examples get removed from it.)

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
Thanks for the contribution! I'll try to make a new release that includes this change soon.

**Comment by bw-yuhogg** [comment]
Also, FYI: very soon I'm going to be looking into the `jsduck` module no longer installing the gem by default. That will affect this module once I bump the dependency on it.

I'll try and publish that as version 1.0.\* so that it doesn't break anyone's code that assumes it gets installed by default.

**Comment by gregjacobs** [comment]
Hey, new version would be great. Currently have the ad-hoc change in my node_modules dir :)

Hmm, why not have the `jsduck` module install the gem by default? Feel like that's a convenient feature. Is it overwriting people's previously-installed jsduck version or something?

**Comment by bw-yuhogg** [comment]
Currently, we first test if the gem already installed, then try gem without sudo and then fall back to sudo if that fails.

I used to think that was fine, until I saw a CPAN module ask me to use sudo in the middle of the installation, which I thought was rather rude. I would prefer not to be a hypocrite :smile:

I realize that for a lot of contexts the automatic installation is useful though. I can't think of a good solution to this at the moment, so let me get back to you about that.

**Comment by bw-yuhogg** [comment]
Also: in case you didn't know, you can point npm directly to a Git repo as a temporary measure until I release a new version.

**Comment by gregjacobs** [comment]
Ah, that makes sense. Yes, definitely rude to ask users to sudo, esp if it's going to fail an entire `npm install` without it! Also, users might not know exactly what they're sudo'ing for when just running `npm install` with a lot of dependencies. Probably just throwing an error during runtime when the jsduck gem itself is not installed with a description of how to install it would be good.

Thanks for the tip on pointing to a git repo with npm btw. I had known about that at some point but it didn't even occur to me for this situation!

**Comment by bw-yuhogg** [comment]
> Probably just throwing an error during runtime when the jsduck gem itself is not installed with a description of how to install it would be good.

Works for me! I'll see about implementing that later this week.

**Comment by bw-yuhogg** [comment]
I've released version 0.3.1, which contains your fix.

However, I should note that I'm not going to be actively developing this module, as my company's not going to be using JSDuck any more. (We're moving to JSDoc). See #13

**Comment by gregjacobs** [comment]
Ah, that's too bad. Thanks for the update though. Why the move from jsduck to jsdoc if you don't mind me asking btw?

**Comment by bw-yuhogg** [comment]
We're not seeing a lot of development activity on JSDuck, and we don't anticipate issues like https://github.com/senchalabs/jsduck/issues/630 getting resolved any time soon.

**Pull request merged**
